version: "2"
services:
  quote:
    image: hecklerm/redisquote
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: hecklerm/redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/markheckler/dev/docker/data/redis:/data
